# Source: drupal/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-release-drupal
  labels:
    app.kubernetes.io/name: drupal
    helm.sh/chart: drupal-13.0.1
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  drupal-password: "dXNlcgo="