# Source: drupal/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-release-mariadb
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-11.4.4
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "azVWUVN5VEJmbg=="
  mariadb-password: "R3dWMGd3eFh1Mg=="